# Generated by Django 5.0.6 on 2024-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_created_at_posts_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Опубликовать пост', verbose_name='Опубликовано?'),
        ),
    ]
